version: '3.9'

services:
  jobmanager:
    build: ./flink_client
    image: apache/flink:1.16-scala_2.12
    hostname: "jobmanager"
    expose:
      - "6123"
    ports:
      - "8081:8081"
    command: jobmanager
    environment:
      - JOB_MANAGER_RPC_ADDRESS=jobmanager
    volumes:
      - ./flink_client/job:/opt/sql-client/job/
  taskmanager:
    image: apache/flink:1.16-scala_2.12
    expose:
      - "6121"
      - "6122"
    depends_on:
      - jobmanager
    command: taskmanager
    links:
      - jobmanager:jobmanager
    environment:
      - JOB_MANAGER_RPC_ADDRESS=jobmanager
networks:
  ndsnet:
    driver: bridge
    name: "fp"
